spring:
  application:
    name: urlshortener
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/admin
  main:
    allow-bean-definition-overriding: true
server:
  port: 9090